SELECT CUSTOMER_ID ,MAX(PURCHASE_AMOUNT) HIGHEST_PO 
FROM ORDERS
GROUP BY CUSTOMER_ID;


SELECT SALESMAN_ID ,MAX(PURCHASE_AMOUNT) HIGHEST_PO 
FROM ORDERS
WHERE ORDER_DATE=TO_DATE('2012/08/17', 'YYYY/MM/DD')
GROUP BY SALESMAN_ID;


SELECT CUSTOMER_ID ,ORDER_DATE,MAX(PURCHASE_AMOUNT) HIGHEST_PO 
FROM ORDERS
HAVING MAX(PURCHASE_AMOUNT) IN (2030, 3450, 5760, 6000)
GROUP BY CUSTOMER_ID ,ORDER_DATE;
