SELECT SUM(PURCHASE_AMOUNT) TOTAL_PURCHASE_AMOUNT 
FROM ORDERS;


SELECT AVG(PURCHASE_AMOUNT) AVERAGE_PURCHASE_AMOUNT 
FROM ORDERS;


SELECT MAX(PURCHASE_AMOUNT) MAX_PURCHASE_AMOUNT 
FROM ORDERS;


SELECT MIN(PURCHASE_AMOUNT) MIN_PURCHASE_AMOUNT 
FROM ORDERS;


SELECT COUNT(DISTINCT SALESMAN_ID) NUM_OF_SALESMAN 
FROM ORDERS;
