UPDATE SALESMAN
SET GRADE=200
WHERE SALESMAN_CITY='Rome';

UPDATE SALESMAN
SET GRADE=300
WHERE SALESMAN_name='James Hoog';



UPDATE SALESMAN
SET SALESMAN_name='Pierre'
WHERE SALESMAN_name='McLyon';